import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Get Started',
      collapsed: false,
      items: [
        'index',
        'installation',
        'getting-started',
        'user-guide/model-types',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Tabular Regression',
          items: [
            'user-guide/python-estimator',
            'user-guide/parameters',
            'objectives',
            'constraints',
            'spatial_modeling',
            'feature_schema',
            'sparse_features',
            'shap',
            'model_artifact',
          ],
        },
        {
          type: 'category',
          label: 'Forecasting',
          collapsed: false,
          items: [
            'forecasting',
            'forecasting_frame',
            'forecasting_api',
            'forecasting_models',
            'forecasting_lag_features',
            'forecasting_backtesting',
            'forecasting_artifacts',
            'forecasting_cli',
            'forecasting_examples',
            {
              type: 'category',
              label: 'Advanced Forecasting',
              collapsed: false,
              items: [
                'forecasting_direct',
                'forecasting_decomposition',
                'forecasting_ensemble',
                'forecasting_reconciliation',
                'forecasting_probabilistic',
                'forecasting_neural',
                'forecasting_overhaul',
                'forecasting_hybridization_assessment',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Model Guides',
          collapsed: false,
          items: [
            'user-guide/forecasting-models/index',
            'user-guide/forecasting-models/auto-forecaster',
            'forecasting_models',
            'user-guide/forecasting-models/naive-seasonal',
            'user-guide/forecasting-models/theta',
            'user-guide/forecasting-models/ets',
            'user-guide/forecasting-models/arima',
            'user-guide/forecasting-models/arima-examples',
            'user-guide/forecasting-models/kalman',
            'user-guide/forecasting-models/kriging',
            'user-guide/forecasting-models/cartoboost-lag',
            'user-guide/forecasting-models/ensembles',
          ],
        },
        'graph-features',
        'neural-features',
        'general_utilities',
        'plotting',
        'user-guide/cli',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: ['reference/python-api', 'reference/cli', 'feature_catalog'],
    },
    {
      type: 'category',
      label: 'Benchmarks',
      collapsed: false,
      items: [
        'benchmarks/index',
        'benchmarks/model-suite',
        'benchmarks/nyc-taxi',
        'benchmarks/forecasting',
        'benchmarks/taxi-zone',
        'benchmarks/lane-level',
        'benchmarks/neural-embedding-benchmark-latest',
      ],
    },
  ],
};

export default sidebars;
