"""Forecasting API for CartoBoost."""

from .artifacts import ForecastArtifact, ForecastArtifactManifest
from .auto import AutoForecaster
from .backtesting import BacktestFoldResult, BacktestResult, RollingOriginBacktester
from .base import BaseForecaster, PanelForecasterMixin, SingleSeriesForecasterMixin
from .config import ForecastingConfig
from .ensemble import WeightedEnsembleForecaster
from .frequency import (
    infer_frequency,
    next_timestamps,
    normalize_frequency,
    validate_horizon,
    validate_regular_frequency,
)
from .global_models import CartoBoostLagForecaster
from .lag_features import (
    CalendarFeatureConfig,
    LagFeatureBuilder,
    LagFeatureConfig,
    RollingFeatureConfig,
)
from .local import (
    AutoARIMAForecaster,
    AutoKalmanForecaster,
    AutoLocalLevelKalmanForecaster,
    AutoStatsBank,
    CrostonForecaster,
    ETSForecaster,
    KalmanForecaster,
    KrigingForecaster,
    LocalLevelKalmanForecaster,
    NaiveForecaster,
    OptimizedThetaForecaster,
    PiecewiseLinearSeasonalForecaster,
    SbaForecaster,
    SeasonalNaiveForecaster,
    ThetaForecaster,
    TsbForecaster,
)
from .metrics import ForecastMetricSet
from .neural import NBEATSForecaster, NBeatsForecaster, NHITSForecaster, NHiTSForecaster
from .registry import ForecastModelSpec, ForecastRegistry
from .schema import ForecastFrame, ForecastResult, PredictionInterval
from .sequence import (
    ReferencePathConfig,
    ReferenceSignal,
    SequenceRow,
    SequenceSeries,
    SequenceStateSpaceConfig,
    forward_ekf,
    generate_group_oof_candidate_rows,
    missing_target_continuation,
    per_group_error_summary,
    reference_path_posterior_mean,
    reference_path_viterbi,
    rts_smoother,
    sequence_blend,
    ukf_reference,
    validate_oof_meta_training,
    validate_sequence_frame,
)
from .splitters import (
    ExpandingWindowSplitter,
    ForecastFold,
    RollingOriginSplitter,
    SlidingWindowSplitter,
)

__all__ = [
    "AutoARIMAForecaster",
    "AutoForecaster",
    "AutoKalmanForecaster",
    "AutoLocalLevelKalmanForecaster",
    "AutoStatsBank",
    "BacktestFoldResult",
    "BacktestResult",
    "BaseForecaster",
    "CalendarFeatureConfig",
    "CartoBoostLagForecaster",
    "CrostonForecaster",
    "ETSForecaster",
    "ExpandingWindowSplitter",
    "ForecastArtifact",
    "ForecastArtifactManifest",
    "ForecastFold",
    "ForecastFrame",
    "ForecastMetricSet",
    "ForecastModelSpec",
    "ForecastRegistry",
    "ForecastResult",
    "ForecastingConfig",
    "infer_frequency",
    "KalmanForecaster",
    "LocalLevelKalmanForecaster",
    "KrigingForecaster",
    "LagFeatureBuilder",
    "LagFeatureConfig",
    "NaiveForecaster",
    "NBEATSForecaster",
    "NBeatsForecaster",
    "NHITSForecaster",
    "NHiTSForecaster",
    "next_timestamps",
    "normalize_frequency",
    "OptimizedThetaForecaster",
    "PanelForecasterMixin",
    "PiecewiseLinearSeasonalForecaster",
    "PredictionInterval",
    "ReferencePathConfig",
    "ReferenceSignal",
    "RollingFeatureConfig",
    "RollingOriginBacktester",
    "RollingOriginSplitter",
    "SbaForecaster",
    "SeasonalNaiveForecaster",
    "SequenceRow",
    "SequenceSeries",
    "SequenceStateSpaceConfig",
    "SingleSeriesForecasterMixin",
    "SlidingWindowSplitter",
    "ThetaForecaster",
    "TsbForecaster",
    "forward_ekf",
    "generate_group_oof_candidate_rows",
    "missing_target_continuation",
    "per_group_error_summary",
    "reference_path_posterior_mean",
    "reference_path_viterbi",
    "rts_smoother",
    "sequence_blend",
    "ukf_reference",
    "validate_oof_meta_training",
    "validate_horizon",
    "validate_regular_frequency",
    "validate_sequence_frame",
    "WeightedEnsembleForecaster",
]
